SELECT 'Upgrading MetaStore schema from 1.2.1000 to 2.0.0' AS MESSAGE;

ALTER TABLE [dbo].[COLUMNS_V2] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[PART_COL_PRIVS] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NULL;
ALTER TABLE [dbo].[TBL_COL_PRIVS] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NULL;
ALTER TABLE [dbo].[SORT_COLS] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NULL;
ALTER TABLE [dbo].[TAB_COL_STATS] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[PART_COL_STATS] ALTER COLUMN [COLUMN_NAME] VARCHAR(1000) NOT NULL;

UPDATE [dbo].[VERSION] SET SCHEMA_VERSION='2.0.0', VERSION_COMMENT='Hive release version 2.0.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 1.2.1000 to 2.0.0' AS MESSAGE;
